# Generated by Django 3.1 on 2020-10-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_timing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
